### ISSUE TITLE
Steps with {float} don't match numbers with > 1 leading digit

### ISSUE THREAD

**Issue by gertvv** [jakubsob/cucumber#1]
I have the following step definition:

```
then("the result is {float}", function(number, context) {
       expect_equal(context$result, number)
})
```

This definition matches the following Gherkin:

```
    Then the result is 1.1
```

But it fails to match the following:

```
    Then the result is 11.1
```

with this error:
```
Caused by error in `parse_step()`:
! No step found for: "Then the result is 11.1"
```

This is not specific to "then" definitions.

(Thanks for this package by the way, it's just what I need!)

**Comment by jakubsob** [comment]
Thanks, @gertvv, for submitting the very first issue!

Let me get back to you on that, it looks like `"11.1"` should be detected just fine (when testing parameter regexes in isolation), so I need to test it more.

I'll dig deeper and inform you about the progress :)

**Comment by gertvv** [comment]
Thanks so much, just installed the latest version from CRAN and works like a charm!
